import React,{useMemo,useState} from "react";import{createRoot}from"react-dom/client";import"./style.css";import{loadData,saveData}from"./storage";import{AppData,Conversation,Message}from"./types";import{buildPrompt}from"./context";import{UnconfiguredProvider}from"./provider";
const id=()=>crypto.randomUUID(); const msg=(text:string,role:"user"|"assistant"):Message=>({id:id(),text,role,createdAt:new Date().toISOString()});
function App(){
 const [data,setData]=useState<AppData>(()=>loadData()); const [active,setActive]=useState<string>(); const [draft,setDraft]=useState(""); const provider=useMemo(()=>new UnconfiguredProvider(),[]);
 const update=(next:AppData)=>{saveData(next);setData(next)}; const current=data.conversations.find(c=>c.id===active);
 function create(){const c:Conversation={id:id(),title:"New conversation",messages:[]};update({...data,conversations:[c,...data.conversations]});setActive(c.id)}
 async function send(){if(!current||!draft.trim())return;const text=draft.trim();const c={...current,messages:[...current.messages,msg(text,"user")]};if(c.messages.length===1)c.title=text.slice(0,48);const next={...data,conversations:data.conversations.map(x=>x.id===c.id?c:x)};update(next);setDraft("");try{buildPrompt(c,next.memories);if(!(await provider.isAvailable()))throw new Error("Cross-platform shell is ready; the local AI runtime is the next migration step.")}catch(e){alert(e instanceof Error?e.message:String(e))}}
 return <main><header><h1>NhomeAI</h1><small>Private cross-platform AI</small></header><section className="layout"><aside><button onClick={create}>+ New chat</button>{data.conversations.map(c=><button className="chat" onClick={()=>setActive(c.id)} key={c.id}>{c.title}</button>)}</aside><article>{current?<><div className="messages">{current.messages.map(m=><div key={m.id} className={m.role}>{m.text}</div>)}</div><form onSubmit={e=>{e.preventDefault();send()}}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Message NhomeAI"/><button>Send</button></form></>:<div className="empty">NhomeAI V1<br/><span>Choose or start a conversation.</span></div>}</article></section></main>
}createRoot(document.getElementById("root")!).render(<App/>);
